import type { FieldDef, ModelDef, Registry } from '../registry/types.js';
import type { Database, Queryable } from '../db/types.js';
import { pgIdentifier } from '../db/identifiers.js';

/**
 * Physical schema derived from the registry, and an Odoo-style `_auto_init`:
 * `syncSchema` creates every missing table, column, relation table, index and
 * foreign key, and never drops or alters existing ones. Because the schema is
 * a pure function of the registry, the registry IS the migration history —
 * exactly how Odoo treats module metadata.
 *
 * Conventions:
 *  - table name = model name with dots → underscores
 *  - every table has `id` (identity) plus the audit columns
 *    `create_uid`, `create_date`, `write_uid`, `write_date`
 *  - one2many fields have no column; many2many fields get a relation table
 *  - binary/image columns hold an attachment reference (S3 key), not bytes
 *  - foreign keys are DEFERRABLE so the seed loader can insert in any order
 */

export interface ColumnSpec {
  name: string;
  sqlType: string;
  notNull?: boolean;
  defaultSql?: string;
  references?: { table: string; onDelete: 'CASCADE' | 'SET NULL' | 'RESTRICT' };
}

export interface TableSpec {
  name: string;
  model?: string;
  columns: ColumnSpec[];
  primaryKey: string[];
  indexes: { name: string; columns: string[] }[];
}

const AUDIT_COLUMNS: ColumnSpec[] = [
  { name: 'create_uid', sqlType: 'integer' },
  { name: 'create_date', sqlType: 'timestamp' },
  { name: 'write_uid', sqlType: 'integer' },
  { name: 'write_date', sqlType: 'timestamp' },
];

export function quoteIdent(name: string): string {
  if (!/^[a-z_][a-z0-9_]*$/i.test(name)) throw new Error(`Unsafe SQL identifier: ${name}`);
  return `"${name}"`;
}

/** SQL type for a stored field, or null when the field has no column. */
export function sqlTypeOf(field: FieldDef): string | null {
  switch (field.type) {
    case 'char':
    case 'selection':
    case 'reference':
      return 'varchar';
    case 'text':
    case 'html':
      return 'text';
    case 'integer':
    case 'many2one':
    case 'many2one_reference':
      return 'integer';
    case 'float':
      return field.digits ? `numeric(${field.digits[0]},${field.digits[1]})` : 'double precision';
    case 'monetary':
      return 'numeric';
    case 'boolean':
      return 'boolean';
    case 'date':
      return 'date';
    case 'datetime':
      return 'timestamp';
    case 'binary':
    case 'image':
      // Attachment reference; payload lives in S3 (A-1 Files).
      return 'varchar';
    case 'json':
    case 'properties':
    case 'properties_definition':
      return 'jsonb';
    case 'one2many':
    case 'many2many':
      return null;
    default:
      return 'varchar';
  }
}

function onDeleteOf(field: FieldDef): 'CASCADE' | 'SET NULL' | 'RESTRICT' {
  if (field.ondelete === 'cascade') return 'CASCADE';
  if (field.ondelete === 'restrict') return 'RESTRICT';
  if (field.ondelete === 'set null') return 'SET NULL';
  // Odoo's defaults: required links restrict, optional links set null.
  return field.required === true ? 'RESTRICT' : 'SET NULL';
}

export function tableFor(model: ModelDef, registry: Registry): TableSpec {
  const columns: ColumnSpec[] = [
    { name: 'id', sqlType: 'integer GENERATED BY DEFAULT AS IDENTITY', notNull: true },
    ...AUDIT_COLUMNS,
  ];
  const indexes: TableSpec['indexes'] = [];

  for (const field of Object.values(model.fields)) {
    if (field.name === 'id' || AUDIT_COLUMNS.some((column) => column.name === field.name)) continue;
    // Always computed from the record name, never stored.
    if (field.name === 'display_name') continue;
    const sqlType = sqlTypeOf(field);
    if (!sqlType) continue;

    const column: ColumnSpec = { name: field.name, sqlType };
    if (field.type === 'many2one' && field.relation && registry.models[field.relation]) {
      column.references = {
        table: registry.models[field.relation].table,
        onDelete: onDeleteOf(field),
      };
      indexes.push({ name: pgIdentifier(`${model.table}_${field.name}_idx`), columns: [field.name] });
    }
    if (field.type === 'boolean') column.defaultSql = 'false';
    columns.push(column);
  }

  return { name: model.table, model: model.name, columns, primaryKey: ['id'], indexes };
}

/** Relation tables, de-duplicated (symmetric pairs share one). */
export function relationTables(registry: Registry): TableSpec[] {
  const seen = new Map<string, TableSpec>();
  for (const model of Object.values(registry.models)) {
    for (const field of Object.values(model.fields)) {
      if (field.type !== 'many2many' || !field.m2mTable || !field.m2mColumn1 || !field.m2mColumn2) continue;
      if (seen.has(field.m2mTable)) continue;
      const comodel = field.relation ? registry.models[field.relation] : undefined;
      seen.set(field.m2mTable, {
        name: field.m2mTable,
        columns: [
          { name: field.m2mColumn1, sqlType: 'integer', notNull: true, references: { table: model.table, onDelete: 'CASCADE' } },
          {
            name: field.m2mColumn2, sqlType: 'integer', notNull: true,
            references: comodel ? { table: comodel.table, onDelete: 'CASCADE' } : undefined,
          },
        ],
        primaryKey: [field.m2mColumn1, field.m2mColumn2],
        indexes: [{ name: pgIdentifier(`${field.m2mTable}_${field.m2mColumn2}_idx`), columns: [field.m2mColumn2] }],
      });
    }
  }
  return [...seen.values()];
}

export function allTables(registry: Registry): TableSpec[] {
  // Transient models get real tables too, as in Odoo: a wizard keeps its
  // state there between the dialog's steps and a cron vacuums old rows.
  const tables = Object.values(registry.models).map((model) => tableFor(model, registry));
  return [...tables, ...relationTables(registry)];
}

/* ------------------------------------------------------------------ *
 * DDL text
 * ------------------------------------------------------------------ */

function columnDdl(column: ColumnSpec): string {
  const parts = [quoteIdent(column.name), column.sqlType];
  if (column.notNull) parts.push('NOT NULL');
  if (column.defaultSql) parts.push(`DEFAULT ${column.defaultSql}`);
  return parts.join(' ');
}

export function createTableDdl(table: TableSpec): string {
  const body = [
    ...table.columns.map(columnDdl),
    `PRIMARY KEY (${table.primaryKey.map(quoteIdent).join(', ')})`,
  ];
  return `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n  ${body.join(',\n  ')}\n)`;
}

export function fkName(table: string, column: string): string {
  return pgIdentifier(`${table}_${column}_fkey`);
}

export function foreignKeyDdl(table: TableSpec, column: ColumnSpec): string | null {
  if (!column.references) return null;
  return `ALTER TABLE ${quoteIdent(table.name)} ADD CONSTRAINT ${quoteIdent(fkName(table.name, column.name))} `
    + `FOREIGN KEY (${quoteIdent(column.name)}) REFERENCES ${quoteIdent(column.references.table)} ("id") `
    + `ON DELETE ${column.references.onDelete} DEFERRABLE INITIALLY IMMEDIATE`;
}

export function indexDdl(table: TableSpec, index: TableSpec['indexes'][number]): string {
  return `CREATE INDEX IF NOT EXISTS ${quoteIdent(index.name)} ON ${quoteIdent(table.name)} (${index.columns.map(quoteIdent).join(', ')})`;
}

/** Complete DDL as one script (for inspection / initial Aurora bootstrap). */
export function generateDdl(registry: Registry): string {
  const tables = allTables(registry);
  const statements: string[] = [];
  for (const table of tables) statements.push(`${createTableDdl(table)};`);
  for (const table of tables) {
    for (const index of table.indexes) statements.push(`${indexDdl(table, index)};`);
  }
  for (const table of tables) {
    for (const column of table.columns) {
      const fk = foreignKeyDdl(table, column);
      if (fk) statements.push(`${fk};`);
    }
  }
  return statements.join('\n');
}

/* ------------------------------------------------------------------ *
 * Sync
 * ------------------------------------------------------------------ */

export interface SyncReport {
  tablesCreated: string[];
  columnsAdded: string[];
  indexesCreated: number;
  foreignKeysAdded: number;
}

async function existingColumns(db: Queryable): Promise<Map<string, Set<string>>> {
  const result = await db.query<{ table_name: string; column_name: string }>(
    `SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = current_schema()`,
  );
  const map = new Map<string, Set<string>>();
  for (const row of result.rows) {
    if (!map.has(row.table_name)) map.set(row.table_name, new Set());
    map.get(row.table_name)!.add(row.column_name);
  }
  return map;
}

async function existingConstraints(db: Queryable): Promise<Set<string>> {
  const result = await db.query<{ conname: string }>(
    `SELECT conname FROM pg_constraint WHERE contype = 'f'`,
  );
  return new Set(result.rows.map((row) => row.conname));
}

/**
 * Bring the database up to the registry. Safe to run on every deploy and on
 * every dev start: it only ever adds.
 */
export async function syncSchema(db: Database, registry: Registry): Promise<SyncReport> {
  const report: SyncReport = { tablesCreated: [], columnsAdded: [], indexesCreated: 0, foreignKeysAdded: 0 };
  const tables = allTables(registry);

  const columns = await existingColumns(db);
  for (const table of tables) {
    const present = columns.get(table.name);
    if (!present) {
      await db.query(createTableDdl(table));
      report.tablesCreated.push(table.name);
      continue;
    }
    for (const column of table.columns) {
      if (present.has(column.name)) continue;
      await db.query(`ALTER TABLE ${quoteIdent(table.name)} ADD COLUMN IF NOT EXISTS ${columnDdl(column)}`);
      report.columnsAdded.push(`${table.name}.${column.name}`);
    }
  }

  for (const table of tables) {
    for (const index of table.indexes) {
      await db.query(indexDdl(table, index));
      report.indexesCreated += 1;
    }
  }

  const constraints = await existingConstraints(db);
  for (const table of tables) {
    for (const column of table.columns) {
      if (!column.references || constraints.has(fkName(table.name, column.name))) continue;
      const ddl = foreignKeyDdl(table, column);
      if (ddl) {
        await db.query(ddl);
        report.foreignKeysAdded += 1;
      }
    }
  }

  return report;
}
